
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int FUNCTION = 16;
  public static final int MULT = 27;
  public static final int ARRAY = 2;
  public static final int MAIORIGUAL = 33;
  public static final int FOR = 7;
  public static final int PONTO = 42;
  public static final int VIRGULA = 39;
  public static final int AND = 35;
  public static final int MENORIGUAL = 34;
  public static final int IGUAL = 29;
  public static final int ACOL = 45;
  public static final int APAR = 43;
  public static final int TYPE = 18;
  public static final int NIL = 15;
  public static final int OR = 36;
  public static final int IN = 11;
  public static final int CLASS = 21;
  public static final int MAIS = 25;
  public static final int FCOL = 46;
  public static final int FPAR = 44;
  public static final int DIV = 28;
  public static final int IF = 3;
  public static final int ID = 49;
  public static final int DPONTOS = 40;
  public static final int OF = 13;
  public static final int EOF = 0;
  public static final int MAIOR = 31;
  public static final int METHOD = 23;
  public static final int PVIRGULA = 41;
  public static final int NEW = 24;
  public static final int error = 1;
  public static final int DIF = 30;
  public static final int MENOS = 26;
  public static final int MENOR = 32;
  public static final int BREAK = 14;
  public static final int IMPORT = 19;
  public static final int ATRIB = 38;
  public static final int BARRA = 37;
  public static final int PRIMITIVE = 20;
  public static final int ELSE = 5;
  public static final int INTEIRO = 50;
  public static final int ACHA = 47;
  public static final int TO = 8;
  public static final int WHILE = 6;
  public static final int FCHA = 48;
  public static final int LET = 10;
  public static final int THEN = 4;
  public static final int EXTENDS = 22;
  public static final int END = 12;
  public static final int STRING = 51;
  public static final int VAR = 17;
  public static final int DO = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ARRAY",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "FOR",
  "TO",
  "DO",
  "LET",
  "IN",
  "END",
  "OF",
  "BREAK",
  "NIL",
  "FUNCTION",
  "VAR",
  "TYPE",
  "IMPORT",
  "PRIMITIVE",
  "CLASS",
  "EXTENDS",
  "METHOD",
  "NEW",
  "MAIS",
  "MENOS",
  "MULT",
  "DIV",
  "IGUAL",
  "DIF",
  "MAIOR",
  "MENOR",
  "MAIORIGUAL",
  "MENORIGUAL",
  "AND",
  "OR",
  "BARRA",
  "ATRIB",
  "VIRGULA",
  "DPONTOS",
  "PVIRGULA",
  "PONTO",
  "APAR",
  "FPAR",
  "ACOL",
  "FCOL",
  "ACHA",
  "FCHA",
  "ID",
  "INTEIRO",
  "STRING"
  };
}

